// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/cloud/gkehub/v1/multiclusteringress/multiclusteringress.proto

package com.google.cloud.gkehub.multiclusteringress.v1;

public final class MultiClusterIngressProto {
  private MultiClusterIngressProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_gkehub_multiclusteringress_v1_FeatureSpec_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_gkehub_multiclusteringress_v1_FeatureSpec_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\nDgoogle/cloud/gkehub/v1/multiclustering" +
      "ress/multiclusteringress.proto\022*google.c" +
      "loud.gkehub.multiclusteringress.v1\032\034goog" +
      "le/api/annotations.proto\"(\n\013FeatureSpec\022" +
      "\031\n\021config_membership\030\001 \001(\tB\266\002\n.com.googl" +
      "e.cloud.gkehub.multiclusteringress.v1B\030M" +
      "ultiClusterIngressProtoP\001Z]google.golang" +
      ".org/genproto/googleapis/cloud/gkehub/mu" +
      "lticlusteringress/v1;multiclusteringress" +
      "\252\002*Google.Cloud.GkeHub.MultiClusterIngre" +
      "ss.V1\312\002*Google\\Cloud\\GkeHub\\MultiCluster" +
      "Ingress\\V1\352\002.Google::Cloud::GkeHub::Mult" +
      "iClusterIngress::V1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.api.AnnotationsProto.getDescriptor(),
        });
    internal_static_google_cloud_gkehub_multiclusteringress_v1_FeatureSpec_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_google_cloud_gkehub_multiclusteringress_v1_FeatureSpec_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_gkehub_multiclusteringress_v1_FeatureSpec_descriptor,
        new java.lang.String[] { "ConfigMembership", });
    com.google.api.AnnotationsProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
